import { describe, it, expect } from 'vitest';
import * as mod from '../src/services/order-service.js';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize api/src/services/order-service.js as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('api/src/services/order-service.js (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["VALID_STATUSES","createOrderService"]);
  });

  it('survives remove-unused-variable at line 8 (javascript:S1481)', () => {
    expect(mod.createOrderService).toBeDefined();
    expect(typeof mod.createOrderService).toBe('function');
    expect(mod.createOrderService.length).toBe(1);
  });

});
