import { describe, it, expect } from 'vitest';
import * as mod from '../src/routes/orders.js';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize api/src/routes/orders.js as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('api/src/routes/orders.js (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["createOrderRouter"]);
  });

  it('survives remove-unused-variable at line 7 (javascript:S1481)', () => {
    expect(mod.createOrderRouter).toBeDefined();
    expect(typeof mod.createOrderRouter).toBe('function');
    expect(mod.createOrderRouter.length).toBe(1);
  });

  it('survives remove-unused-import at line 2 (javascript:S1128)', () => {
    expect(Object.keys(mod).sort()).toEqual(["createOrderRouter"]);
  });

});
