import { describe, it, expect } from 'vitest';
import * as mod from '../src/store.js';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize api/src/store.js as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('api/src/store.js (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["createStore"]);
  });

  it('survives remove-unused-variable at line 13 (javascript:S1481)', () => {
    expect(mod.createStore).toBeDefined();
    expect(typeof mod.createStore).toBe('function');
    expect(mod.createStore.length).toBe(0);
  });

});
