import { describe, it, expect } from 'vitest';
import * as mod from '../src/reports/summary.js';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize api/src/reports/summary.js as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('api/src/reports/summary.js (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["averageTotal","buildSummary","countOpen","countPending","highestTotal","peakOrderValue","toCents"]);
  });

  it('survives to-optional-chain at line 97 (javascript:S6582)', () => {
    expect(mod.buildSummary).toBeDefined();
    expect(typeof mod.buildSummary).toBe('function');
    expect(mod.buildSummary.length).toBe(2);
  });

  it('survives to-optional-chain at line 87 (javascript:S6582)', () => {
    expect(mod.buildSummary).toBeDefined();
    expect(typeof mod.buildSummary).toBe('function');
    expect(mod.buildSummary.length).toBe(2);
  });

  it('survives to-optional-chain at line 78 (javascript:S6582)', () => {
    expect(mod.buildSummary).toBeDefined();
    expect(typeof mod.buildSummary).toBe('function');
    expect(mod.buildSummary.length).toBe(2);
  });

  it('survives remove-dead-store at line 51 (javascript:S1854)', () => {
    expect(mod.averageTotal).toBeDefined();
    expect(typeof mod.averageTotal).toBe('function');
    expect(mod.averageTotal.length).toBe(1);
  });

  it('survives var-to-const at line 9 (javascript:S3504)', () => {
    expect(Object.keys(mod).sort()).toEqual(["averageTotal","buildSummary","countOpen","countPending","highestTotal","peakOrderValue","toCents"]);
  });

  it('survives var-to-const at line 8 (javascript:S3504)', () => {
    expect(Object.keys(mod).sort()).toEqual(["averageTotal","buildSummary","countOpen","countPending","highestTotal","peakOrderValue","toCents"]);
  });

});
