import { describe, it, expect } from 'vitest';
import * as mod from './order.service';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize web/src/app/orders/order.service.ts as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('web/src/app/orders/order.service.ts (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["OrderService"]);
  });

  it('survives remove-unused-import at line 3 (typescript:S1128)', () => {
    expect(Object.keys(mod).sort()).toEqual(["OrderService"]);
  });

});
