import { describe, it, expect } from 'vitest';
import * as mod from './order-stats';

// GENERATED by the remediation run — one case per applied fix.
//
// These characterize web/src/app/orders/order-stats.ts as it was before remediation. They do not
// assert the code smells are gone; they assert the module still presents
// the surface it did, which is what a fix that deleted the wrong line
// would break.
describe('web/src/app/orders/order-stats.ts (characterized before remediation)', () => {
  it('exports the same names it did before remediation', () => {
    expect(Object.keys(mod).sort()).toEqual(["OrderStats"]);
  });

  it('survives var-to-const at line 10 (typescript:S3504)', () => {
    expect(Object.keys(mod).sort()).toEqual(["OrderStats"]);
  });

  it('survives var-to-const at line 9 (typescript:S3504)', () => {
    expect(Object.keys(mod).sort()).toEqual(["OrderStats"]);
  });

});
